name: Trigger API on Folder Change

on:
  push:
    branches:
      - main

jobs:
  send-api-calls:
    runs-on: ubuntu-latest
    env:
      DEV_API_URL: ${{ vars.DEV_API_URL }}
      PREPROD_API_URL: ${{ vars.PREPROD_API_URL }}
      PROD_API_URL: ${{ vars.PROD_API_URL }}
      DEV_API_TOKEN: ${{ secrets.DEV_TOKEN }}
      PREPROD_API_TOKEN: ${{ secrets.PREPROD_TOKEN }}
      PROD_API_TOKEN: ${{ secrets.PROD_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get list of changed files
        id: changes
        run: |
          echo "Changed files between HEAD and HEAD^:"
          git diff --name-only HEAD^ HEAD
      
          CHANGED_FILES="$(git diff --name-only HEAD^ HEAD)"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Debug print CHANGED_FILES
        run: |
          echo "Files changed:"
          echo "$CHANGED_FILES"

      - name: Send API POST requests for changed files
        run: |
          echo "Changed files:"
          echo "$CHANGED_FILES"

          post_if_changed() {
            folder=$1
            url=$2
            token=$3
            file_path="$folder/features.json"

            if echo "$CHANGED_FILES" | grep -q "^$file_path$"; then
              echo "📤 Triggering POST to $url (no request body)"
              curl -X POST "$url" \
                -H "Authorization: Bearer $token"
            else
              echo "✅ No change in $file_path"
            fi
          }

          post_if_changed "dev" "$DEV_API_URL" "DEV_API_TOKEN"
          post_if_changed "preprod" "$PREPROD_API_URL" "PREPROD_API_TOKEN"
          post_if_changed "prod" "$PROD_API_URL" "PROD_API_TOKEN"
