name: Trigger API on Folder Change

on:
  push:
    branches:
      - main

jobs:
  deploy-and-trigger:
    runs-on: ubuntu-latest
    env:
      DEV_API_URL: ${{ vars.DEV_API_URL }}
      PREPROD_API_URL: ${{ vars.PREPROD_API_URL }}
      PROD_API_URL: ${{ vars.PROD_API_URL }}
      DEV_API_TOKEN: ${{ secrets.DEV_TOKEN }}
      PREPROD_API_TOKEN: ${{ secrets.PREPROD_TOKEN }}
      PROD_API_TOKEN: ${{ secrets.PROD_TOKEN }}
      GCP_BUCKET: ${{ vars.GCP_BUCKET }}
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get list of changed files
        run: |
          CHANGED_FILES="$(git diff --name-only HEAD^ HEAD)"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Upload changed configs to GCS
        run: |
          upload_if_changed() {
            folder=$1
            file_path="$folder/features.json"

            if echo "$CHANGED_FILES" | grep -q "^$file_path$"; then
              echo "⬆️ Uploading $file_path to gs://${GCP_BUCKET}/$folder/"
              gsutil cp "$file_path" "gs://${GCP_BUCKET}/$folder/"
            else
              echo "✅ No change in $file_path, skipping upload"
            fi
          }

          upload_if_changed "dev"
          upload_if_changed "preprod"
          upload_if_changed "prod"

      - name: Send API POST requests for changed files
        run: |
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          post_if_changed() {
            folder=$1
            url=$2
            token=$3
            file_path="$folder/features.json"

            if echo "$CHANGED_FILES" | grep -q "^$file_path$"; then
              echo "📤 Triggering POST to $url (no request body)"
              curl -X POST "$url" \
                -H "Authorization: Bearer $token"
            else
              echo "✅ No change in $file_path"
            fi
          }

          post_if_changed "dev" "$DEV_API_URL" "DEV_API_TOKEN"
          post_if_changed "preprod" "$PREPROD_API_URL" "PREPROD_API_TOKEN"
          post_if_changed "prod" "$PROD_API_URL" "PROD_API_TOKEN"
